name: loterias
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.3+43
# version: 2.3.2+4
# version: 2.5.0+41

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^5.0.0
  get_it: ^7.1.1
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  http: ^0.13.3
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  sembast: ^3.0.2
  sembast_web: '>=1.0.0'
  # sembast: ^2.4.8+1
  # flutter_share_me: ^0.9.1
  # socket_io_client: ^0.9.9
  # corsac_jwt: ^0.1.2
  # adhara_socket_io: ^0.4.2+1
  sqflite: ^2.0.0+3
  barcode_scan: ^2.0.1
  charts_flutter: ^0.10.0
  # package_info: ^0.4.0+17
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  timezone: ^0.7.0
  shimmer: ^1.1.1
  # workmanager: ^0.2.3
  jiffy: ^4.1.0
  flutter_native_timezone: ^1.0.4
  unicons: ^2.0.1
  scrollable_positioned_list: ^0.1.10
  horizontal_data_table: ^3.1.0
  jose: ^0.3.0
  moor: ^4.2.1
  moor_flutter: ^4.0.0
  socket_io_client: ^1.0.1
  file_picker: ^3.0.0
  syncfusion_flutter_datepicker: ^19.1.66-beta
  device_info_plus: ^2.0.1
  ntp: ^2.0.0
  pdf: ^3.4.2
  printing: ^5.4.1
  qr_flutter: ^4.0.0
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  moor_generator: ^4.2.2
  build_runner:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/ProductSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
   
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
